version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - echo Pre-build phase
      - npm install
  build:
    commands:
      - echo Build phase
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: dist
